### ISSUE TITLE
功能请求

### ISSUE THREAD

**Issue by NewBugger** [nondanee/Nroxy#5]
希望增加 Notification 和 Foreground   running 功能

在仅运行 Nodejs  runtime  时，没有 foreground  状态会导致服务被杀，而 Android 26+ 要求前台进程必须有通知提醒（也希望 vpn 运行时能有 mini 级别通知）

本人能力不足不会写实现，希望作者能考虑，感谢

**Comment by nondanee** [comment]
本人能力也不足，不会写==

**Comment by nondanee** [comment]
只需要 node 环境建议用 dorynode
https://play.google.com/store/apps/details?id=io.tempage.dorynode

**Comment by nondanee** [comment]
还想着要做通知栏快捷磁贴和桌面 shortcuts，可惜都不会，太难了

**Comment by NewBugger** [comment]
回信快的人真的很棒啊 （玩梗）

本人因为第一次接触 Android app 开发，没有学过语言。有尝试看 Android developer 文档，无奈不会语言，哭了

**Comment by NewBugger** [comment]
现在就是用的 dorynode

dorynode 有个很蠢的设定：只能写两条 argument，而且对于 -a xxx 格式的脚本，会因为 dorynode 写作 '-a xxx' 而运行不能（说的就是网易云脚本）

**Comment by NewBugger** [comment]
报告一下，作者你的项目：
一、inspect code - c/c++ 部分报错无数，argument not available 等
二、make build - 也是在 c 部分警告无数

**Comment by nondanee** [comment]
C 的部分也不是我写的 (我也不会写) 😂
看 Credit 第一个项目
https://github.com/forbe/tun2http

**Comment by NewBugger** [comment]
我现在遇到 crash 无法启动程序。c 部分本来就是报错吗

**Comment by nondanee** [comment]
不知道你咋启动的 😂
和 jni 有关联，应该不能直接启动吧
travis ci 能正常 build，应该就没问题吧

**Comment by nondanee** [comment]
看了下你 fork 的
改包名的话这些也要改的
https://github.com/NewBugger/Nroxy-Android/blob/47ffcf560aa905dde41aa210a4b619e59d7080a8/app/src/main/cpp/tun2http/tun2http.c#L75
不改 build 不了的

**Comment by NewBugger** [comment]
———回信快的人真棒啊

感谢，为了方便折腾就换了包名。作者的版本我在用

**Comment by NewBugger** [comment]
> 看了下你 fork 的
> 改包名的话这些也要改的
> https://github.com/NewBugger/Nroxy-Android/blob/47ffcf560aa905dde41aa210a4b619e59d7080a8/app/src/main/cpp/tun2http/tun2http.c#L75
> 不改 build 不了的

可以用一个变量表示这个路径（包名）吗

**Comment by nondanee** [comment]
不知道，知识盲区==

**Comment by nondanee** [comment]
dorynode 那个问题我看了下确实==
那你只要再加一个额外的启动脚本就行，然后把参数写里面

```js
#!/usr/bin/env node
Array.prototype.push.apply(process.argv, '-p 8080:8081 -a 127.0.0.1 -o qq'.split(/\s/g))
require('./app')
```

**Comment by NewBugger** [comment]
> dorynode 那个问题我看了下确实==
> 那你只要再加一个额外的启动脚本就行，然后把参数写里面
> 
> ```js
> #!/usr/bin/env node
> Array.prototype.push.apply(process.argv, '-p 8080:8081 -a 127.0.0.1 -o qq'.split(/\s/g))
> require('./app')
> ```

谢。端口为什么那样写

**Comment by nondanee** [comment]
这样写对 6.3 之下的版本装证书就能解决主页打不开的问题

**Comment by NewBugger** [comment]
> ———回信快的人真棒啊
> 
> 感谢，为了方便折腾就换了包名。作者的版本我在用

我放弃了，还是 crash 的我。本来起码想换上 arm64 的 node

**Comment by NewBugger** [comment]
> > ———回信快的人真棒啊
> > 感谢，为了方便折腾就换了包名。作者的版本我在用
> 
> 我放弃了，还是 crash 的我。本来起码想换上 arm64 的 node

![Capture](https://user-images.githubusercontent.com/41441631/77079611-444d1480-6a33-11ea-80fb-3001992022d7.PNG)

**Comment by NewBugger** [comment]
logcat
```cmd
FATAL EXCEPTION: main
Process: io.github.newbugger.android.nroxy, PID: 23848
java.lang.RuntimeException: Unable to start activity ComponentInfo{io.github.newbugger.android.nroxy/io.github.newbugger.android.nroxy.MainActivity}: android.view.InflateException: Binary XML file line #17: Binary XML file line #17: Error inflating class TextContainer
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2951)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3086)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1816)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6718)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
Caused by: android.view.InflateException: Binary XML file line #17: Binary XML file line #17: Error inflating class TextContainer
Caused by: android.view.InflateException: Binary XML file line #17: Error inflating class TextContainer
Caused by: java.lang.ClassNotFoundException: Didn't find class "android.view.TextContainer" on path: DexPathList[[zip file "/data/app/io.github.newbugger.android.nroxy-JkoLDLvEPelzxJWmwmnQAg==/base.apk"],nativeLibraryDirectories=[/data/app/io.github.newbugger.android.nroxy-JkoLDLvEPelzxJWmwmnQAg==/lib/arm64, /data/app/io.github.newbugger.android.nroxy-JkoLDLvEPelzxJWmwmnQAg==/base.apk!/lib/arm64-v8a, /system/lib64]]
	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
	at android.view.LayoutInflater.createView(LayoutInflater.java:606)
	at android.view.LayoutInflater.onCreateView(LayoutInflater.java:703)
	at com.android.internal.policy.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:68)
	at android.view.LayoutInflater.onCreateView(LayoutInflater.java:720)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:788)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:730)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:863)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:374)
	at android.support.v7.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:469)
	at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:140)
	at io.github.newbugger.android.nroxy.MainActivity.onCreate(MainActivity.java:47)
	at android.app.Activity.performCreate(Activity.java:7144)
	at android.app.Activity.performCreate(Activity.java:7135)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2931)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3086)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1816)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6718)
```

**Comment by nondanee** [comment]
> Didn't find class "android.view.TextContainer"

`TextContainer` 是自定义的组件，不在 `android.view` 里
应该要带包名的，我看你都去掉了，应该不行吧

https://github.com/NewBugger/Nroxy-Android/commit/7829cdd3eb10c7f0832d55ab57705a2755b964dc

**Comment by NewBugger** [comment]
既然 inspection 不报错，我觉得应该可以省略  
感谢，我尝试

———回信快的人真的很棒啊

**Comment by nondanee** [comment]
是 nodejs.org 上的 arm64 release 吗？
那个用不了的，不用试了
我用的二进制包来自 dorynode
没找到更高的能用的版本
看下 Credit

**Comment by NewBugger** [comment]
> 是 nodejs.org 上的 arm64 release 吗？
> 那个用不了的，不用试了
> 我用的二进制包来自 dorynode
> 没找到更高的能用的版本
> 看下 Credit

不能用的原因能找到吗  
dorynode 只有 arm，版本号倒是不要紧

**Comment by nondanee** [comment]
原因不太懂，你可以看看这个
https://github.com/sjitech/build-nodejs-for-android

版本号不要紧的话 credit 最后一个项目里有很多 arm64 的二进制包可以用

**Comment by NewBugger** [comment]
> 原因不太懂，你可以看看这个
> https://github.com/sjitech/build-nodejs-for-android
> 
> 版本号不要紧的话 credit 最后一个项目里有很多 arm64 的二进制包可以用

它版本超旧，我自己编译吧

**Comment by nondanee** [comment]
你不是说版本号不要紧吗😂

**Comment by NewBugger** [comment]
> 你不是说版本号不要紧吗😂

6.0 7.0 过分了

**Comment by NewBugger** [comment]
> > Didn't find class "android.view.TextContainer"
> 
> `TextContainer` 是自定义的组件，不在 `android.view` 里
> 应该要带包名的，我看你都去掉了，应该不行吧
> 
> [NewBugger@7829cdd](https://github.com/NewBugger/Nroxy-Android/commit/7829cdd3eb10c7f0832d55ab57705a2755b964dc)

失败了，一样的报错。

**Comment by NewBugger** [comment]
> > Didn't find class "android.view.TextContainer"
> 
> `TextContainer` 是自定义的组件，不在 `android.view` 里
> 应该要带包名的，我看你都去掉了，应该不行吧
> 
> [NewBugger@7829cdd](https://github.com/NewBugger/Nroxy-Android/commit/7829cdd3eb10c7f0832d55ab57705a2755b964dc)

感谢，是 TextView 需要包名。作者是自己造的轮子吗，去掉包名会报错 android.textview not allowed here.

**Comment by nondanee** [comment]
```diff
-    <TextContainer
+    <io.github.newbugger.android.nroxy.TextContainer
```

我看你 commit 是 TextContainer 啊 😂
不是轮子

包一层 container 是因为 textview 自带的滚动没有滚动惯性，没有 overscroll 效果，太难看

**Comment by NewBugger** [comment]
> ```diff
> -    <TextContainer
> +    <io.github.newbugger.android.nroxy.TextContainer
> ```
> 
> 我看你 commit 是 TextContainer 啊 😂
> 不是轮子
> 
> 包一层 container 是因为 textview 自带的滚动没有滚动惯性，没有 overscroll 效果，太难看

我转 kotlin 被卡了好久，哭了

———回信快的人真的很棒啊

**Comment by NewBugger** [comment]
文件类型不能这样定义吗，在 DocumentUI 没有筛选效果，还导致无法选中 js 文件
```kotlin
            if (!permitStorage()) return
            val intent = Intent(Intent.ACTION_GET_CONTENT)
            intent.type = "Application/JavaScript"
            intent.addCategory(Intent.CATEGORY_OPENABLE)
```

**Comment by NewBugger** [comment]
`deprecated in java` 真多啊，尤其是 android.preference.preference*

**Comment by nondanee** [comment]
应该是 `text/javascript` 吧
不知道啊，可能我当初也试过 `text/javascript` 没法选文件才换成 `*/*` 的吧

**Comment by NewBugger** [comment]
> 应该是 `text/javascript` 吧
> 不知道啊，可能我当初也试过 `text/javascript` 没法选文件才换成 `*/*` 的吧

这个定义不能 filter 就没必要了

**Comment by nondanee** [comment]
咦，我怎么没看到 `deprecated in java` 提示啊
难道我用了个假的 Android Studio 😂？

**Comment by NewBugger** [comment]
不应该。编译应该有 warning

**Comment by NewBugger** [comment]
有很多 deprecated，却只能替换一小部分

**Comment by nondanee** [comment]
嗯？在哪里看的啊 😂
我看这个全都是 c 的 warning 啊 (我也不会改==)

![image](https://user-images.githubusercontent.com/26399680/77233067-03463300-6be0-11ea-8aab-a8e87354f4c1.png)

**Comment by NewBugger** [comment]
> 嗯？在哪里看的啊 
> 我看这个全都是 c 的 warning 啊 (我也不会改==)
> 
> ![image](https://user-images.githubusercontent.com/26399680/77233067-03463300-6be0-11ea-8aab-a8e87354f4c1.png)

不科学，你用新 dependencies 看看

**Comment by NewBugger** [comment]
我记得的有可以换 androidx.appcompat androidx.test 等等

**Comment by nondanee** [comment]
我建了新的项目，自动生成的是 androidx.appcompat
但是我建这个项目的时候生成的就是 v7 啊 😂
8 太懂
明天升升看

**Comment by NewBugger** [comment]
> 我建了新的项目，自动生成的是 androidx.appcompat
> 但是我建这个项目的时候生成的就是 v7 啊 
> 8 太懂
> 明天升升看

怎样自动生成

**Comment by nondanee** [comment]
new Project 生成的 build.gradle 是这样的
```gradle
dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])

    implementation 'androidx.appcompat:appcompat:1.0.2'
    implementation 'androidx.constraintlayout:constraintlayout:1.1.3'
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'androidx.test.ext:junit:1.1.1'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.2.0'
}
```

**Comment by NewBugger** [comment]
> new Project 生成的 build.gradle 是这样的
> 
> ```groovy-gradle
> dependencies {
>     implementation fileTree(dir: 'libs', include: ['*.jar'])
> 
>     implementation 'androidx.appcompat:appcompat:1.0.2'
>     implementation 'androidx.constraintlayout:constraintlayout:1.1.3'
>     testImplementation 'junit:junit:4.12'
>     androidTestImplementation 'androidx.test.ext:junit:1.1.1'
>     androidTestImplementation 'androidx.test.espresso:espresso-core:3.2.0'
> }
> ```

挺好的，虽然还不是最新

**Comment by NewBugger** [comment]
我想把 c 的部分移除掉（移除 vpn 的部分），做单独 nodejs 移动应用。

c 的部分报错太多以免牵连。

dorynode 也不开源，哎

**Comment by nondanee** [comment]
只做 node 我觉得没啥意义，可视化配置可有可无，还不如用 termux

**Comment by NewBugger** [comment]
> 只做 node 我觉得没啥意义，可视化配置可有可无，还不如用 termux

快住口，整个应用的意义都要没了

**Comment by NewBugger** [comment]
来人扶我起来，我还能写 notification。。

**Comment by NewBugger** [comment]
踩坑了，binary 会在 target 29 被 SELinux 拦下来

**Comment by NewBugger** [comment]
> 只做 node 我觉得没啥意义，可视化配置可有可无，还不如用 termux

补充一句：只能写应用，terminal 哪来权限跑 binary，还需要 root 权限使用 /data

**Comment by nondanee** [comment]
你没用过 termux 吗？API 29 以下就有权限跑啊，为什么要使用 /data，你要访问别的应用的 /data ？
没人逼你一定要使用 API 29，起码现在没有
( play 商店都没你心急 https://developer.android.com/distribute/best-practices/develop/target-sdk )
他们应该比你专业，你觉得 termux 没救了可以直接去 https://github.com/termux/termux-app/issues/1072 扁鹊三连

**Comment by NewBugger** [comment]
> 你没用过 termux 吗？API 29 以下就有权限跑啊，为什么要使用 /data，你要访问别的应用的 /data ？
> 没人逼你一定要使用 API 29，起码现在没有
> ( play 商店都没你心急 https://developer.android.com/distribute/best-practices/develop/target-sdk )
> 他们应该比你专业，你觉得 termux 没救了可以直接去 [termux/termux-app#1072](https://github.com/termux/termux-app/issues/1072) 扁鹊三连

是我没说清楚。我说的是如果自己准备 binary，需要放进 /data 才有执行权限

**Comment by NewBugger** [comment]
做个记录，今天已经扶起不来了
```cmd
E/AndroidRuntime: Process: io.github.newbugger.android.nroxy
E/AndroidRuntime: java.lang.RuntimeException: Unable to instantiate service io.github.newbugger.android.nroxy.ShellService: kotlin.KotlinNullPointerException
E/AndroidRuntime: 	at io.github.newbugger.android.nroxy.ShellService.<init>(ShellService.kt:30)
W/ActivityTaskManager:   Force finishing activity io.github.newbugger.android.nroxy/.MainActivity
```
在 Notification 部分的 this（context）总是报错空值，被它玩一天了都 
https://github.com/NewBugger/Nroxy-Android/blob/d8344238d6a841f036ca715c95ddb3dd1a07b094/app/src/main/java/io/github/newbugger/android/nroxy/ShellService.kt#L30

**Comment by NewBugger** [comment]
> 做个记录，今天已经扶起不来了
> 
> ```batchfile
> E/AndroidRuntime: Process: io.github.newbugger.android.nroxy
> E/AndroidRuntime: java.lang.RuntimeException: Unable to instantiate service io.github.newbugger.android.nroxy.ShellService: kotlin.KotlinNullPointerException
> E/AndroidRuntime: 	at io.github.newbugger.android.nroxy.ShellService.<init>(ShellService.kt:30)
> W/ActivityTaskManager:   Force finishing activity io.github.newbugger.android.nroxy/.MainActivity
> ```
> 
> 在 Notification 部分的 this（context）总是报错空值，被它玩一天了都
> https://github.com/NewBugger/Nroxy-Android/blob/d8344238d6a841f036ca715c95ddb3dd1a07b094/app/src/main/java/io/github/newbugger/android/nroxy/ShellService.kt#L30

喜报，notification + foreground service 已成功 https://github.com/NewBugger/Nroxy-Android/commit/1520552f2ad1d36fbd9b4073ae344e1e1c1a53e4

**Comment by laggardkernel** [comment]
自己打了一个 Newbugger 的包，希望可以常驻不被杀。

---

@NewBugger 兄弟，编译好的包有吗，来一个 

我是配合 Clash 使用，在升级 clash for Android 到某个版本后。重启这个代理服务会报错

```
{ Error: read ECONNRESET
    at TLSWrap.onStreamRead (internal/stream_base_commons.js:111:27) errno: 'ECONNRESET', code: 'ECONNRESET', syscall: 'read' }
```
