### ISSUE TITLE
不支持 Android 10

### ISSUE THREAD

**Issue by nondanee** [nondanee/Nroxy#7]
https://developer.android.com/about/versions/10/privacy/changes#proc-net-filesystem

> 对 `/proc/net` 文件系统的访问权限实施了限制

https://github.com/nondanee/Nroxy/blob/7933f070216b2e2e30d36e92e390e9564107089b/app/src/main/cpp/tun2http/ip.c#L321-L333

导致 `get_uid` 出错

```
type=1400 audit(0.0:13003): avc: denied { read } for name="tcp" dev="proc" ino=4026532086 scontext=u:r:untrusted_app_27:s0:c512,c768 tcontext=u:object_r:proc_net_tcp_udp:s0 tclass=file permissive=0
```

需使用 `getConnectionOwnerUid`（Called from C code)

https://developer.android.com/reference/android/net/ConnectivityManager.html#getConnectionOwnerUid(int,%20java.net.InetSocketAddress,%20java.net.InetSocketAddress)

参考
https://stackoverflow.com/questions/58497492/acccess-to-proc-net-tcp-in-android-q

**Comment by NewBugger** [comment]
nodejs 部分可以使用，vpn 部分容我试下

**Comment by NewBugger** [comment]
而且，node binary（target 29）被拦下
```cmd
W sh : avc: granted { execute } for name="node" scontext=u:r:untrusted_app:s0 tcontext=u:object_r:app_data_file:s0 tclass=file
W sh : avc: denied { execute_no_trans } for path="..nroxy/files/usr/bin/node" scontext=u:r:untrusted_app:s0 tcontext=u:object_r:app_data_file:s0 tclass=file permissive=0
```

**Comment by nondanee** [comment]
@NewBugger 这个问题不大

**Comment by NewBugger** [comment]
> @NewBugger 这个问题不大

怎样的问题不大，node 也不能跑了

**Comment by nondanee** [comment]
@NewBugger targetAPI 不要升 29 还是可以用的啊

**Comment by NewBugger** [comment]
> @NewBugger targetAPI 不要升 29 还是可以用的啊

plan C 吗（震惊）

**Comment by NewBugger** [comment]
有无接口能查询 package installation dir /data/app/name-*

**Comment by nondanee** [comment]
`getApplicationInfo().nativeLibraryDir`

**Comment by NewBugger** [comment]
> `getApplicationInfo().nativeLibraryDir`

感谢。我试了一圈都返回 /data/data

———回信快的人太棒了

**Comment by nondanee** [comment]
关于 Android 10 运行 binary file 的问题

https://developer.android.com/ndk/guides/wrap-script#packaging_wrapsh
放在 `src/main/resources/lib/` 中的二进制文件只在 debug 打包中可以 extract
(其实 release 打包可以看到有 `lib/` 有文件，但 nativeLibraryDir 里就是没有)

没搜到解决方法
https://stackoverflow.com/questions/58753615/native-libraries-not-installed-in-release-build
https://issuetracker.google.com/u/0/issues/147972074

现在用了假名字 libnode.so，可以正确 extract，类似如下这个改动
(必须放在 jniLibs/，必须命名为 libxxx.so)
https://github.com/devgianlu/aria2lib/pull/8/files#diff-ffa122908d75bd2b6cdb03fad044c33fR101

https://stackoverflow.com/questions/5583487/hosting-an-executable-within-android-application/58748468#58748468
用 `new File(getfilesDir().getParentFile(), 'lib')` 这个地址肯定不对

附:
termux 相关讨论 https://github.com/termux/termux-app/issues/1072
v2ex 相关讨论 https://www.v2ex.com/t/597716

**Comment by NewBugger** [comment]
> 关于 Android 10 运行 binary file 的问题
> 
> https://developer.android.com/ndk/guides/wrap-script#packaging_wrapsh
> 放在 `src/main/resources/lib/` 中的二进制文件只在 debug 打包中可以 extract
> (其实 release 打包可以看到有 `lib/` 有文件，但 nativeLibraryDir 里就是没有)
> 
> 没搜到解决方法
> https://stackoverflow.com/questions/58753615/native-libraries-not-installed-in-release-build
> https://issuetracker.google.com/u/0/issues/147972074
> 
> 现在用了假名字 libnode.so，可以正确 extract，类似如下这个改动
> (必须放在 jniLibs/，必须命名为 libxxx.so)
> https://github.com/devgianlu/aria2lib/pull/8/files#diff-ffa122908d75bd2b6cdb03fad044c33fR101
> 
> https://stackoverflow.com/questions/5583487/hosting-an-executable-within-android-application/58748468#58748468
> 用 `new File(getfilesDir().getParentFile(), 'lib')` 这个地址肯定不对
> 
> 附:
> termux 相关讨论 [termux/termux-app#1072](https://github.com/termux/termux-app/issues/1072)
> v2ex 相关讨论 https://www.v2ex.com/t/597716

jniLibs 可行，但在跑 js 报错如：
```
fs.js:115
    throw err;
    ^

Error: EACCES: permission denied, open '/storage/emulated/0/.../js/app-conf.js'
    at Object.openSync (fs.js:439:3)
    at Object.readFileSync (fs.js:344:35)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:20)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:743:3)

```

**Comment by nondanee** [comment]
看了下又是 29 的限制
https://developer.android.com/training/data-storage/files/external-scoped#java
没意思，28 又不是不能用

**Comment by NewBugger** [comment]
> 看了下又是 29 的限制
> https://developer.android.com/training/data-storage/files/external-scoped#java
> 没意思，28 又不是不能用

太难了

**Comment by NewBugger** [comment]
> 看了下又是 29 的限制
> https://developer.android.com/training/data-storage/files/external-scoped#java
> 没意思，28 又不是不能用

app-specific data 也不行，不是存储权限的问题吧

**Comment by nondanee** [comment]
那估计是命令行 access file 都不行了，不管 app 有没有权限

**Comment by NewBugger** [comment]
```cmd
ActivityManager: Start proc 8759:io.github.newbugger.android.nroxy/u0a190 for service {io.github.newbugger.android.nroxy/io.github.newbugger.android.nroxy.ShellService}
ActivityManager: Stopping service due to app idle: u0a190 -1m31s233ms io.github.newbugger.android.nroxy/.ShellService
ActivityThread: handleStopService: token=android.os.BinderProxy@79391d not found.
ActivityManager: Service done with onDestroy, but executeNesting=2: ServiceRecord{b1ff5f u0 io.github.newbugger.android.nroxy/.ShellService}
ActivityTaskManager: START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=io.github.newbugger.android.nroxy/.MainActivity bnds=[798,669][1056,1070]} from uid 10146
ActivityTaskManager: START u0 {cmp=io.github.newbugger.android.nroxy/.PreferenceActivity} from uid 10190
TaskPersister: File error accessing recents directory (directory doesn't exist?).
ActivityTaskManager: START u0 {cmp=io.github.newbugger.android.nroxy/.PreferenceActivity} from uid 10190
TaskPersister: File error accessing recents directory (directory doesn't exist?).
```

**Comment by NewBugger** [comment]
> ```batchfile
> ActivityManager: Start proc 8759:io.github.newbugger.android.nroxy/u0a190 for service {io.github.newbugger.android.nroxy/io.github.newbugger.android.nroxy.ShellService}
> ActivityManager: Stopping service due to app idle: u0a190 -1m31s233ms io.github.newbugger.android.nroxy/.ShellService
> ActivityThread: handleStopService: token=android.os.BinderProxy@79391d not found.
> ActivityManager: Service done with onDestroy, but executeNesting=2: ServiceRecord{b1ff5f u0 io.github.newbugger.android.nroxy/.ShellService}
> ActivityTaskManager: START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=io.github.newbugger.android.nroxy/.MainActivity bnds=[798,669][1056,1070]} from uid 10146
> ActivityTaskManager: START u0 {cmp=io.github.newbugger.android.nroxy/.PreferenceActivity} from uid 10190
> TaskPersister: File error accessing recents directory (directory doesn't exist?).
> ActivityTaskManager: START u0 {cmp=io.github.newbugger.android.nroxy/.PreferenceActivity} from uid 10190
> TaskPersister: File error accessing recents directory (directory doesn't exist?).
> ```

看不懂这日志，尝试 copy .js to dataDir.

**Comment by NewBugger** [comment]
> 那估计是命令行 access file 都不行了，不管 app 有没有权限

指定脚本路径在 app-specific data 实测可行（https://github.com/NewBugger/Nroxy-Android/commit/424ef922cfedf1fb2ef2fb0cbc60f88a07b1cacd）

新出现的问题： jniLibs/libnode.so exec() 不受 Android 和 .shellservice 两者控制，在短时间后 exec 被系统收回，但 .shellservice 被应用自己判断为并未结束（可能？），结果是在应用内开启关闭再开启将报错：port 8080 already in use。尝试添加 stopshell（https://github.com/NewBugger/Nroxy-Android/commit/c081240cb24ef2fe3bf451222a78d17a61564f86）效果失败。

**Comment by nondanee** [comment]
是把 script 位置写死了吗？那有什么用？

**Comment by NewBugger** [comment]
> 是把 script 位置写死了吗？那有什么用？

只要读 external storage 就会触发报错。写死在 app-specific data 也不是太要紧，自己复制一份就好

**Comment by NewBugger** [comment]
请问 .ShellService 和 Runtime.exec 是什么关系？

在启动服务的几分钟后 .ShellService 被系统杀掉，但经由 ShellService 运行的 Runtime.exec 依旧在后台存活
```
W ActivityManager: Stopping service due to app idle: u0a190 -1m6s166ms io.github.newbugger.android.nroxy/.ShellService
```

.ShellService 被杀掉，导致 nroxy 应用判断服务终止，启动开关切换至 off，再次启动按钮，但此时 Runtime 还存活着
```
address already in use
```

划卡片或 force stop 应用后，ShellService 已经死掉不需要再回收，Runtime 在此时也被回收，因此重启应用可再次启动 on 按钮

作者的原作品可能是判断 vpn() 所以开关不会跳 off？我只判断 ShellService 所以会掉开关。

Runtime.exec 不受 .ShellService 和 Android 管理，生命周期如何决定。即使把 ShellService 提至 foreground 也未必能保活？

**Comment by nondanee** [comment]
都会判
我又不懂安卓开发。。。
有 notification 应该不会被杀掉

https://github.com/nondanee/Nroxy/blob/d3ecc15c43614905c08c218e8d98e22a57c6715c/app/src/main/java/dev/nondanee/nroxy/ShellService.java#L121-L125

感觉可能和这个有关系，换个位置试一下
https://www.jianshu.com/p/0aa29c9f9ab3

这周很忙，没空管

**Comment by NewBugger** [comment]
> 都会判
> 我又不懂安卓开发。。。
> 有 notification 应该不会被杀掉
> 
> https://github.com/nondanee/Nroxy/blob/d3ecc15c43614905c08c218e8d98e22a57c6715c/app/src/main/java/dev/nondanee/nroxy/ShellService.java#L121-L125
> 
> 感觉可能和这个有关系，换个位置试一下
> https://www.jianshu.com/p/0aa29c9f9ab3
> 
> 这周很忙，没空管

打扰了，可以有空再回我
